>P1;P11018
structureX:P11018:1: : 272  : :  : : -1.00 :-1.00
VNELPEGIKVIKAPEMWAKGVKGKNIKVAVLDTGCDTSHPDLK-NQIIG-----GKNFTD
DDGGKEDAISDYNGHGTHVAGTIAAND--SNGGIAGVAPEASLLIVKVLGGENGSGQYEW
IINGINYAV-EQKVDIISMSLGG------PSDVPELKEAVKNAVKNGVLVVCAAGNEGDG
DERTEELSYPAAYNEVIAVGSVSVARELSEFSNANKEI-------DLVAPGENILSTLPN
KK---YGKLTGTSMAAPHVSGALALIKSYEEESFQRKLSESEVFAQLIRRTLPLD-----
------------------IA*
>P1;1sbhA
structureX:1sbhA:1: : 274  : :  : : -1.00 :-1.00
AQSVPYGVSQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPDLK--------VAGGASFVP
SE---TNPFQDNNSHGTHVAGTVAAL--DNSIGVLGVAPSASLYAVKVLGADG-SGQYSW
IINGIEWAI-ANNMDVINMSLGG------PSGSAALKAAVDKAVASGVVVVAAAGNEGTS
GSSS-TVGYPAKYPSVIAVGAVDSSNQRASFSSVGPEL-------DVMAPGVSI-STLPG
NK---YGAYSGTSMASPHVAGAAALILS-----KHPNWTNTQVRSSLENTTTYLG-----
-DSFYYGKGLINVQAA--AQ*
>P1;1yjaA
structureX:1yjaA:1: : 274  : :  : : -1.00 :-1.00
AQSVPYGVSQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPDLK--------VAGGASFVP
SE---TNPFQDNNSHGTHVAGTVAAL--DNSIGVLGVAPSASLYAVKVLGADG-SGQYSW
IINGIEWAI-ANNMDVINMSLGG------PSGSAALKAAVDKAVASGVVVVAAAGNEGTS
GSSS-TVGYPAKYPSVIAVGAVDSSNQRASFSSVGPEL-------DVMAPGVSI-STLPG
NK---YGAYSGTSMASPHVAGAAALILS-----KHPNWTNTQVRSSLENTTTYLG-----
-DSFYYGKGLINVQAA--AQ*
>P1;1yjbA
structureX:1yjbA:1: : 274  : :  : : -1.00 :-1.00
AQSVPYGVSQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPDLK--------VAGGASFVP
SE---TNPFQDNNSHGTHVAGTVAAL--DNSIGVLGVAPSASLYAVKVLGADG-SGQYSW
IINGIEWAI-ANNMDVINMSLGG------PSGSAALKAAVDKAVASGVVVVAAAGNEGTS
GSSS-TVGYPAKYPSVIAVGAVDSSNQRASFSSVGPEL-------DVMAPGVSI-STLPG
NK---YGAYSGTSMASPHVAGAAALILS-----KHPNWTNTQVRSSLENTTTYLG-----
-DSFYYGKGLINVQAA--AQ*
