>P1;P11018
structureX:P11018:1: : 289  : :  : : -1.00 :-1.00
------------------MVNELPEGIKVIKAPEMWAKGVKGKNIKVAVLDTGCDTSHPD
LKNQIIGGKNFTDDDGGKEDAISDYNGHGTHVAGTIAANDSNGGIAGVAPEASLLIVKVL
GGENGSGQYEWIINGINYAVEQKVDIISMSLGGPSDVPELKEAVKNAVKNGVLVVCAAGN
EGDGDERTEELSYPAAYNEVIAVGSVSVARELSEFSNANKEIDLVAPGENILSTLPNKKY
GKLTGTSMAAPHVSGALALIKSYEEESFQRKLSESEVFAQLIRRTLPLDIAKTLAGNGFL
YLTAPDE------------*
>P1;1sbhA
structureX:1sbhA:1: : 274  : :  : : -1.00 :-1.00
-------------------AQSVPYGVSQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPD
LKVAGGASFVPSETNPFQDNNS-----HGTHVAGTVAALDNSIGVLGVAPSASLYAVKVL
GA-DGSGQYSWIINGIEWAIANNMDVINMSLGGPSGSAALKAAVDKAVASGVVVVAAAGN
EGTSG-SSSTVGYPAKYPSVIAVGAVDSSNQRASFSSVGPELDVMAPGVSI-STLPGNKY
GAYSGTSMASPHVAGAAALILSKHPN-----WTNTQVRSSLENTTTYLGDS-FYYGKGLI
NVQAAAQ------------*
>P1;1s01A
structureX:1s01A:1: : 275  : :  : : -1.00 :-1.00
-------------------AQSVPYGVSQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPD
LKVAGGASFVPSETNPFQDNNS-----HGTHVAGTVAALDNSIGVLGVAPSASLYAVKVL
GA-DGSGQYSWIINGIEWAIANNMDVINMSLGGPSGSAALKAAVDKAVASGVVVVAAAGN
EGTSG-SSSTVGYPAKYPSVIAVGAVDSSNQRASFSSVGPELDVMAPGVSICSTLPGNKY
GAKSGTSMASPHVAGAAALILSKHPN-----WTNTQVRSSLENTTTKLGDS-FYYGKGLI
NVQAAAQ------------*
>P1;1sbiA
structureX:1sbiA:1: : 274  : :  : : -1.00 :-1.00
-------------------AQSVPYGVSQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPD
LKVAGGASFVPSETNPFQDNNS-----HGTHVAGTVAALDNSIGVLGVAPSASLYAVKVL
GA-DGSGQYSWIINGIEWAIANNMDVINMSLGGPSGSAALKAAVDKAVASGVVVVAAAGN
EGTSG-SSSTVGYPAKYPSVIAVGAVDSSNQRASFSSVGPELDVMAPGVSI-STLPGNKY
GAYSGTSMASPHVAGAAALILSKHPN-----WTNTQVRSSLENTTTKLGDS-FYYGKGLI
NVQAAAQ------------*
