>P1;P11018
structureX:P11018:1: : 283  : :  : : -1.00 :-1.00
QIMDVNELPEGIKVIKAPEMWAKGVKGKNIKVAVLDTGCDTSHPDLKNQIIGGKNFTDDD
GGKEDAISDYNGHGTHVAGTIAANDSNGGIAGVAPEASLLIVKVLGGENGSGQYEWIING
INYAVEQKVDIISMSLGGPSDVPELKE---------------------------------
-----------------------------------A------------------------
---------------VKNAVKNGVLVVCAAGNEGDGDERTEELSYPAAYNEVIAVGSVSV
ARELSEFSNANKEIDLVAPGENILSTLPNKKYGKLTGTSMAAPHVSGALALIKSYEEESF
QRKLSESEVFAQLIRRTLPLDIAKTLAGNG*
>P1;1abwA
structureX:1abwA:1: : 283  : :  : : -1.00 :-1.00
MLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGK
KVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPA
VHASLDKFLASVSTVLTSKYRGVLSPAD--------------------------------
------------------------------------------------------------
---------------KTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHG
SAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAA
HLPAEFTPAVHASLDKFLASVSTVLTSKYR*
>P1;1o1nA
structureX:1o1nA:1: : 282  : :  : : -1.00 :-1.00
MLSPADKTNVKAAWGKVGAHAGEYGAEAWERMFLSFPTTKTYFPHFDLSHGSAQVKGHGK
KVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPA
VHASLDKFLASVSTVLTSKYRVLSPAD---------------------------------
------------------------------------------------------------
--------------KTNVKAAWGKVGAHAGEYGAEAWERMFLSFPTTKTYFPHFDLSHGS
AQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAH
LPAEFTPAVHASLDKFLASVSTVLTSKYR*
