>P1;target
structureX:target:1: : 166  : :  : : -1-00 :-1-00
ATKAICILKGDGPVQGTLSSLS---------------LHFEAKGDEGGDTIVITGSLTGL
TEGDHGWHIHQWGDN-TQGCTSAGPLFNPLSKKLGGPKDEERVVGDLGNITADKNGVALI
DLIDPLLSLSGEYSLLGRTMVIHEKPLVLGRGGNEELMIQNSTKKTGNAGSRLACGV-LG
LAK*
>P1;1cbj_A
structureX:1cbj_A:1: : 151  : :  : : -1-00 :-1-00
-------------------ATKAVCVLKG-DGPVQGTIHFEAKG--DT--VVVTGSITGL
TEGDHGFHVHQFGDN-TQGCTSAGPHFNPLSKKHGGPKDEERHVGDLGNVTADKNGVAIV
DIVDPLISLSGEYSIIGRTMVVHEKPDDLGRG------GNEESTKTGNAGSRLACGVIGI
AK-*
>P1;1q0e_A
structureX:1q0e_A:1: : 151  : :  : : -1-00 :-1-00
-------------------ATKAVCVLKG-DGPVQGTIHFEAKG--DT--VVVTGSITGL
TEGDHGFHVHQFGDN-TQGCTSAGPHFNPLSKKHGGPKDEERHVGDLGNVTADKNGVAIV
DIVDPLISLSGEYSIIGRTMVVHEKPDDLGRG------GNEESTKTGNAGSRLACGVIGI
AK-*
>P1;1sda_B
structureX:1sda_B:1: : 150  : :  : : -1-00 :-1-00
-------------------ATKAVCVLKG-DGPVQGTIHFEAKG--DT--VVVTGSITGL
TEGDHGFHVHQFGDN-TQGCTSAGPHFNPLSKKHGGPKDEERHVGDLGNVTADKNGVAIV
DIVDPLISLS-GESIIGRTMVVHEKPDDLGRG------GNEESTKTGNAGSRLACGVIGI
AK-*
