>P1;target
structureX:target:1: : 166  : :  : : -1.00 :-1.00
ATKAICILKGDGPVQGTLSSLSLHFEAKGDEGGDTIVITGSLTGLTEGDHGWHIHQWGDN
TQGCTSAGPLFNPLSKKLGGPKDEERVVGDLGNITADKNGVALIDLIDPLLSLSGEYSLL
GRTMVIHEKPLVLGRGGNEELMIQNSTKKTGNAGSRLACGVLGLAK*
>P1;1cbj_A
structureX:1cbj_A:1: : 151  : :  : : -1.00 :-1.00
ATKAVCVLKGDGPVQGT-----IHFEAKG----DTVVVTGSITGLTEGDHGFHVHQFGDN
TQGCTSAGPHFNPLSKKHGGPKDEERHVGDLGNVTADKNGVAIVDIVDPLISLSGEYSII
GRTMVVHEKPDDLGRGGNEE-----S-TKTGNAGSRLACGVIGIAK*
>P1;1q0e_A
structureX:1q0e_A:1: : 151  : :  : : -1.00 :-1.00
ATKAVCVLKGDGPVQGT-----IHFEAKG----DTVVVTGSITGLTEGDHGFHVHQFGDN
TQGCTSAGPHFNPLSKKHGGPKDEERHVGDLGNVTADKNGVAIVDIVDPLISLSGEYSII
GRTMVVHEKPDDLGRGGNEE-----S-TKTGNAGSRLACGVIGIAK*
>P1;1cob_A
structureX:1cob_A:1: : 151  : :  : : -1.00 :-1.00
ATKAVCVLKGDGPVQGT-----IHFEAKG----DTVVVTGSITGLTEGDHGFHVHQFGDN
TQGCTSAGPHFNPLSKKHGGPKDEERHVGDLGNVTADKNGVAIVDIVDPLISLSGEYSII
GRTMVVHEKPDDLGRGGNEE-----S-TKTGNAGSRLACGVIGIAK*
