>P1;1mdy
structureX:1mdy:1:A:401:C:  : : -1.00 :-1.00
AQSVPYGISQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPDLN--VRGGASFVP---SET
NPYQDGSSHGTHVAGTIAALNNSIGVLGVAPSASLYAVKVLDST-GSGQYSWIINGIEWA
ISNNMDVINMSLGGPTGSTALKTVVDKAVSSGIVVAAAAGNEGSSGS-TSTVGYPAKYPS
TIAVGAVNSANQRASFSSAGSELDVMAPGVSIQSTLPGGTYGAYNGTSMATPHVAGAAAL
ILSKHPTWTNAQVRDR------------LESTATYLGSSFYYGKGLINVQAAAQ/
LKSFPEVVGKTVDQAREYFTLHYPQYNVYFLPEGSPVTLDLRYNRVRVFYNPGTNVVNHVPHVG/
..*
>P1;P11018
structureX:P11018:1:A:401:I:  : : -1.00 :-1.00
VNELPEGIKVIKAPEMWAKGVKGKNIKVAVLDTGCDTSHPDLKNQIIGGKNFTDDDGGKE
DAISDYNGHGTHVAGTIAANDSNGGIAGVAPEASLLIVKVLGGENGSGQYEWIINGINYA
VEQKVDIISMSLGGPSDVPELKEAVKNAVKNGVLVVCAAGNEGDGDERTEELSYPAAYNE
VIAVGSVSVARELSEFSNANKEIDLVAPGENILSTLPNKKYGKLTGTSMAAPHVSGALAL
IKSYEEESFQRKLSESEVFAQLIRRTLPLDIAKTLAGNGFLYLTAPDELAEKAE/
LKSFPEVVGKTVDQAREYFTLHYPQYNVYFLPEGSPVTLDLRYNRVRVFYNPGTNVVNHVPHVG/
..*
