>P1;1mdy
structureX:1mdy:1:E:166:D :  : : -1.00 :-1.00
............../
............../
............../
............../
MELKRKTTNAD------RRKAATMRERRRLSKVNEAFETLKRSTSS-NPNQRLPKVEILR
NAIRYIEGLQALLRD/
TTNADRRKAATMRERRRLSKVNEAFETLKRSTSSNPN-QRLPKVEILRNAIRYIEGLQAL
LRD/
TTNADRRKAATMRERRRLSKVNEAFETLKRSTSSNPNQRLPKVEILRNAIRYIEGLQALLRD/
TTNADRRKAATMRERRRLSKVNEAFETLKRSTSSNPNQRLPKVEILRNAIRYIEGLQALLRD*


>P1;target
structureX:Q62414:1:A:166:B :  : : -1.00 :-1.00
............../
............../
............../
............../
--KKRKMTKARLERSKLRRQKANARERNRMHDLNAALDNLRKVVPCYSKTQKLSKIETLR
LAKNYIWALSEILRS/
-----RRLKANNRERNRMHNLNAALDALREVLPTFPEDAKLTKIETLRFAHNYIWALTET
LR-/
--------------------------------------------------------------/
--------------------------------------------------------------*
