>P1;1gri_A
structureX:1gri_A:1: : 211  : :  : : -1.00 :-1.00
MEAIAKYDFKATADDELSFKRGDILKVQNWYKAELNGKDGFIPKNYIEMKPHPWFFGKIP
RAKAEEMLSKQRHDGAFLIRESESAPGDFSLSVKFGNDVQHFKVLRDGAGKYFLWVVKFN
SLNELVDYHRSTSVSRNQQIFLRDIEQVPQQPTYVQALFDFDPQEDGELGFRRGDFIHVM
DNSDPNWWKGACHGQTGMFPRNYVTPVNRNV*
>P1;1bmb_A
structureX:1bmb_A:1: : 98  : :  : : -1.00 :-1.00
-------------------------------------------------KPHPWFFGKIP
RAKAEEMLSKQRHDGAFLIRESESAPGDFSLSVKFGNDVQHFKVLRDGAGKYFLWVVKFN
SLNELVDYHRSTSVSRNQQIFLRDIEQ---------------------------------
-------------------------------*
>P1;1fyr_D
structureX:1fyr_D:1: : 95  : :  : : -1.00 :-1.00
---------------------------------------------------HPWFFGKIP
RAKAEEMLSKQRHDGAFLIRESESAPGDFSLSVKFGNDVQHFKVLRDGAGKYFLWVVKFN
SLNELVDYHRSTSVSRNQQIFLRDIE----------------------------------
-------------------------------*
