>P1;1gri_A
structureX:1gri_A:1: : 211  : :  : : -1.00 :-1.00
MEAIAKYDFKATADDELSFKRGDILKVQ------NWYKAELNGKDGFIPKNYIEMKPHPW
FFGKIPRAKAEEMLSKQRHDGAFLIRESESAPGDFSLSVKFGNDVQHFKVLRDGAGKYFL
WVVKFNSLNELVDYHRSTSVSRNQQIFLRDIEQVPQQP--TYVQALFDFDPQEDGELGFR
RGDFIHVMDNSDPNWWKGACHGQTGMFPRNYVTPVNRNV*
>P1;1fyr_D
structureX:1fyr_D:1: : 95  : :  : : -1.00 :-1.00
---------------------------------------------------------HPW
FFGKIPRAKAEEMLSKQRHDGAFLIRESESAPGDFSLSVKFGNDVQHFKVLRDGAGKYFL
WVVKFNSLNELVDYHRSTSVSRNQQIFLRDIE----------------------------
---------------------------------------*
>P1;1bmb_A
structureX:1bmb_A:1: : 98  : :  : : -1.00 :-1.00
-------------------------------------------------------KPHPW
FFGKIPRAKAEEMLSKQRHDGAFLIRESESAPGDFSLSVKFGNDVQHFKVLRDGAGKYFL
WVVKFNSLNELVDYHRSTSVSRNQQIFLRDIEQ---------------------------
---------------------------------------*
>P1;target
structureX:target:1: : 217  : :  : : -1.00 :-1.00
MESVALYSFQATESDELAFNKGDTLKILNMEDDQNWYKAELRGVEGFIPKNYIRVKPHPW
YSGRISRQLAEEILMKRNHLGAFLIRESESSPGEFSVSVNYGDQVQHFKVLREASGKYFL
WEEKFNSLNELVDFYRTTTIAKKRQIFLRDEEPLLKSPGACFAQAQFDFSAQDPSQLSFR
RGDIIEVLERPDPHWWRGRSCGRVGFFPRSYVQPVHL--*
