>P1;p9c_domain2_A
structureX:p9c_domain2_with_chains:54:A:129:A:  : : -1.00 :-1.00
WFFGKIPRAKAEEMLSKQRHDGAFLIRESESAPGDFSLSVKFGNDVQHFKVLRDGAGKYF
LWVVKFNSLNELVDYH*
>P1;p9c_domain2_B
structureX:p9c_domain2_with_chains:3:D:78:D:  : : -1.00 :-1.00
WFFGKIPRAKAEEMLSKQRHDGAFLIRESESAPGDFSLSVKFGNDVQHFKVLRDGAGKYF
LWVVKFNSLNELVDYH*
>P1;p9c_domain2_C
structureX:p9c_domain2_with_chains:5:C:80:C:  : : -1.00 :-1.00
WFFGKIPRAKAEEMLSKQRHDGAFLIRESESAPGDFSLSVKFGNDVQHFKVLRDGAGKYF
LWVVKFNSLNELVDYH*
>P1;target
structureX:target:1: : 47  : :  : : -1.00 :-1.00
WYSGRISRQLAEEILMKRNHLGAFLIRESESSPGEFSVSVNYGDQVQHFKVLREASGKYF
LWEEKFNSLNELVDFY*
