>P1;target
structureX:target:1: : 287  : :  : : -1.00 :-1.00
-HKCHLCGRAFRTVTLLRNHLNTHTGTRPHKCPDCDMAFVTSGELVRHRRYKHTHEKPFK
CSMCDYASVEVSKLKRHIRSHTGERPFQCSLCSYASRDTYKLKRHMRTHSGEKPYEAYIN
HARFTQSGTMKMNILQKSTENVAKFHDPHSDTVIARKSDLGVSLRKQSSYIEQGKKCRYC
DAVFHERYALIQHQKSHKNEKRFKCDQCDYASRQERHMIMHKRTHTGEKPYACSHCDKTF
RQKQLLDMHFKRYHDPNFVPAAFVCSKCGKTFTRRNTMARHADNCAGP*
>P1;5tou_A
structureX:5tou_A:1: : 170  : :  : : -1.00 :-1.00
THKCHLCGRAFRTVTLLRNHLNTHTGTRPHKCPDCDMAFVTSGELVRHRRYKHTHEKPFK
CSMCDYASVEVSKLKRHIRSHTGERPFQCSLCSYASRDTYKLKRHMRTHSGEKPYECYIC
HARFTQSGTMKMHILQKHTENVAKFHCPHCDTVIARKSDLGVHLRKQHSY----------
------------------------------------------------------------
------------------------------------------------*
>P1;5yel_B
structureX:5yel_B:1: : 168  : :  : : -1.00 :-1.00
------------------------------------------------------------
---------------------------------------------------KPYECYICH
ARFTQSGTMKMHILQK---HVAKFHCPHCDTVIARKSDLGVHLRKQHSYIEQGKKCRYCD
AVFHERYALIQHQKSHKNEKRFKCDQCDYASRQERHMIMHKRTHTG-KPYACSHCDKTFR
QKQLLDMHFKRYHDP--VPAAFVCSKCGKTFTRRNTMARHADNCA-*
