>P1;target
structureX:target:1: : 287  : :  : : -1.00 :-1.00
HKCHLCGRAFRTVTLLRNHLNTHTGTRPHKCPDCDMAFVTSGELVRHRRYKHTHEKPFKC
SMCDYASVEVSKLKRHIRSHTGERPFQCSLCSYASRDTYKLKRHMRTHSGEKPYEAYINH
ARFTQSGTMKMNILQKSTENVAKFHDPHSDTVIARKSDLGVSLRKQSSYIEQGKKCRYCD
AVFHERYALIQHQKSHKNEKRFKCDQCDYASRQERHMIMHKRTHTGEKPYACSHCDKTFR
QKQLLDMHFKRYHDPNFVPAAFVCSKCGKTFTRRNTMARHADNCAGP---*
>P1;5YEL
structureX:5YEL:1: : 176  : :  : : -1.00 :-1.00
------------------------------------------------------------
---------------------------------------------------KPYECYICH
ARFTQSGTMKMHILQKHTENVAKFHCPHCDTVIARKSDLGVHLRKQHSYIEQGKKCRYCD
AVFHERYALIQHQKSHKNEKRFKCDQCDYASRQERHMIMHKRTHTGEKPYACSHCDKTFR
QKQLLDMHFKRYHDPNFVPAAFVCSKCGKTFTRRNTMARHADNCAGP---*
>P1;5T0U
structureX:5T0U:1: : 177  : :  : : -1.00 :-1.00
------------------------------------------------------------
------------------------------------------------PLGSTHKCHLCG
RAFRTVTLLRNH-LNTHTG-TRPHKCPDCDMAFVTSGELVRHRRYKHTH-EKPFKCSMCD
YASVEVSKLKRHIRSHTGERPFQCSLCSYASRDTYKLKRHMRTHSGEKPYECYICHARFT
QSGTMKMHILQKHTEN--VAKFHCPHCDTVIARKSDLGVHLRKQHSYIEQ*
