>P1;target
structureX:target:1: : 287  : :  : : -1.00 :-1.00
HKCHLCGRAFRTVTLLRNHLNTHTGTRPHKCPDCDMAFVTSGELVRHRRYKHTHEKPFKC
SMCDYASVEVSKLKRHIRSHTGERPFQCSLCSYASRDTYKLKRHMRTHSGEKPYEAYINH
ARFTQSGTMKMNILQKSTENVAKFHDPHSDTVIARKSDLGVSLRKQSSYIEQGKKCRYCD
AVFHERYALIQHQKSHKNEKRFKCDQCDYASRQERHMIMHKRTHTGEKPYACSHCDKTFR
QKQLLDMHFKRYHDPNFVPAAFVCSKCGKTFTRRNTMARHADNCAGP*
>P1;5tou_A
structureX:5tou_A:1: : 170  : :  : : -1.00 :-1.00
------------------------------------------------------------
----------------------------------------------------THKCHLCG
RAFRTVTLLRNHLNTHT--GTRPHKCPDCDMAFVTSGELVRHRRYKHTH-EKPFKCSMCD
YASVEVSKLKRHIRSHTGERPFQCSLCSYASRDTYKLKRHMRTHSGEKPYECYICHARFT
QSGTMKMHILQKHTEN--VAKFHCPHCDTVIARKSDLGVHLRKQHSY*
>P1;5yel_B
structureX:5yel_B:1: : 168  : :  : : -1.00 :-1.00
------------------------------------------------------------
---------------------------------------------------KPYECYICH
ARFTQSGTMKMHILQK---HVAKFHCPHCDTVIARKSDLGVHLRKQHSYIEQGKKCRYCD
AVFHERYALIQHQKSHKNEKRFKCDQCDYASRQERHMIMHKRTHTG-KPYACSHCDKTFR
QKQLLDMHFKRYHDP--VPAAFVCSKCGKTFTRRNTMARHADNCA--*

