>P1;1meeA
structureX:1meeA:1: : 275  : :  : : -1.00 :-1.00
------------------AQSVPYGISQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPDL
N--VRGGASFVP---SETNPYQDGSSHGTHVAGTIAALNNSIGVLGVAPSASLYAVKVLD
S-TGSGQYSWIINGIEWAISNNMDVINMSLGGPTGSTALKTVVDKAVSSGIVVAAAAGNE
GSSGS-TSTVGYPAKYPSTIAVGAVNSANQRASFSSAGSELDVMAPGVSIQSTLPGGTYG
AYNGTSMATPHVAGAAALILSKHPTWTN---------AQVRDR---LESTATYLGSSFYY
GKGLINVQAAAQ-------*
>P1;P11018
structureX:P11018:1: : 319  : :  : : -1.00 :-1.00
MNGEIRLIPYVTNEQIMDVNELPEGIKVIKAPEMWAKGVKGKNIKVAVLDTGCDTSHPDL
KNQIIGGKNFTDDDGGKEDAISDYNGHGTHVAGTIAANDSNGGIAGVAPEASLLIVKVLG
GENGSGQYEWIINGINYAVEQKVDIISMSLGGPSDVPELKEAVKNAVKNGVLVVCAAGNE
GDGDERTEELSYPAAYNEVIAVGSVSVARELSEFSNANKEIDLVAPGENILSTLPNKKYG
KLTGTSMAAPHVSGALALIKSYEEESFQRKLSESEVFAQLIRRTLPLDIAKTLAGNGFLY
LTAPDELAEKAEQSHLLTL*
>P1;1meeI
structureX:1meeI:1: : 64  : :  : : -1.00 :-1.00
------------------------------------------------------------
--------------------------------------------LKSFP-------EVVG
KTVDQAR-EYFT--LHYP---QYNVYFLPEGSP---------------------------
---------VTLDLRYNRVRVF-----------YN----------PGTNVVNHVP--HVG
------------------------------------------------------------
-------------------*
