>P1;1meeA
structureX:1meeA:1: : 275  : :  : : -1.00 :-1.00
AQSVPYGISQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPDLN--VRGGASFVP---SET
NPYQDGSSHGTHVAGTIAALNNSIGVLGVAPSASLYAVKVLDST-GSGQYSWIINGIEWA
ISNNMDVINMSLGGPTGSTALKTVVDKAVSSGIVVAAAAGNEGSSGS-TSTVGYPAKYPS
TIAVGAVNSANQRASFSSAGSELDVMAPGVSIQSTLPGGTYGAYNGTSMATPHVAGAAAL
ILSKHPTWTNAQVRDR------------LESTATYLGSSFYYGKGLINVQAAAQ*
>P1;1scjA
structureX:1scjA:1: : 275  : :  : : -1.00 :-1.00
AQSVPYGISQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPDLN--VRGGASFVP---SET
NPYQDGSSHGTHVAGTIAALNNSIGVLGVSPSASLYAVKVLDST-GSGQYSWIINGIEWA
ISNNMDVINMSLGGPTGSTALKTVVDKAVSSGIVVAAAAGNEGSSGS-TSTVGYPAKYPS
TIAVGAVNSSNQRASFSSAGSELDVMAPGVSIQSTLPGGTYGAYNGTCMATPHVAGAAAL
ILSKHPTWTNAQVRDR------------LESTATYLGNSFYYGKGLINVQAAAQ*
>P1;1sbhA
structureX:1sbhA:1: : 274  : :  : : -1.00 :-1.00
AQSVPYGVSQIKAPALHSQGYTGSNVKVAVIDSGIDSSHPDLK--VAGGASFVP---SET
NPFQDNNSHGTHVAGTVAALDNSIGVLGVAPSASLYAVKVLGAD-GSGQYSWIINGIEWA
IANNMDVINMSLGGPSGSAALKAAVDKAVASGVVVVAAAGNEGTSGS-SSTVGYPAKYPS
VIAVGAVDSSNQRASFSSVGPELDVMAPGVSIS-TLPGNKYGAYSGTSMASPHVAGAAAL
ILSKHPNWTNTQVRSS------------LENTTTYLGDSFYYGKGLINVQAAAQ*
>P1;P11018
structureX:P11018:1: : 294  : :  : : -1.00 :-1.00
VNELPEGIKVIKAPEMWAKGVKGKNIKVAVLDTGCDTSHPDLKNQIIGGKNFTDDDGGKE
DAISDYNGHGTHVAGTIAANDSNGGIAGVAPEASLLIVKVLGGENGSGQYEWIINGINYA
VEQKVDIISMSLGGPSDVPELKEAVKNAVKNGVLVVCAAGNEGDGDERTEELSYPAAYNE
VIAVGSVSVARELSEFSNANKEIDLVAPGENILSTLPNKKYGKLTGTSMAAPHVSGALAL
IKSYEEESFQRKLSESEVFAQLIRRTLPLDIAKTLAGNGFLYLTAPDELAEKAE*
