>P1;2v5l_A
structureX:2v5l_A:1: : 249  : :  : : -1.00 :-1.00
SKPQPIAAANWKCNGSQQSLSELIDLFNSTSINHDVQCVVASTFVHLAMTKERLSHPKFV
IAAQNAIAKSGAFTGEVSLPILKDFGVNWIVLGHSERRAYYGETNEIVADKVAAAVASGF
MVIACIGETLQERESGRTAVVVLTQIAAIAKKLKKADWAKVVIAYEPVWAIGTGKVATPQ
QAQEAH-------ALIRSWVSSKIGADVAGELRILYGGSVNGKNARTLYQQRDVNGFLVG
GASLKPEFVDIIKATQ--------------------------------------------
----------------------*
>P1;6tim_A
structureX:6tim_A:1: : 249  : :  : : -1.00 :-1.00
SKPQPIAAANWKCNGSQQSLSELIDLFNSTSINHDVQCVVASTFVHLAMTKERLSHPKFV
IAAQNAIAKSGAFTGEVSLPILKDFGVNWIVLGHSERRAYYGETNEIVADKVAAAVASGF
MVIACIGETLQERESGRTAVVVLTQIAAIAKKLKKADWAKVVIAYEPVWAIGTGKVATPQ
QAQEAH-------ALIRSWVSSKIGADVAGELRILYGGSVNGKNARTLYQQRDVNGFLVG
GASLKPEFVDIIKATQ--------------------------------------------
----------------------*
>P1;problema40
structureX:problema40:1: : 245  : :  : : -1.00 :-1.00
------------------------------------------------------------
SLPILKDFGVNWIVLGHSERRAYYGETNEIVADKVAAAVASGFMVIACIGETLQERESGR
TAVVVLTQIAAIAKKLKKADWAKVVIAYEPVWAIGTGKVATPQQAQEAHALAHSSLALIR
SWVSSKIGADVAGELRILYGGSVNGKNARTLYQQRDVNGFLVGGASLKPEFVDIIKATQS
KPQPIAAANWKCNGSQQSLSELIDLFNSTSINHDVQCVVASTFVHLAMTKERLSHPKFVIA
AQNA---------------------------------------------------------
----------------------*
