>P1;8cpa_A
structureX:8cpa_A:1: : 307  : :  : : -1.00 :-1.00
ARSTNTFNYATYHTLDEIYDFMDLLVAQHPELVSKLQIGRSYEGRPIYVLKFSTGGSNRP
AIWIDLGIHSREWITQATGVWFAKKFTENYGQNPSFTAILDSMDIFLEIVTNPNGFAFTH
SENRLWRKTRSVTSSSLCVGVDANRNWDAGFGKAGASSSPCSETYHGKYANSEVEVKSIV
DFVKNHGNFKAFLSIHSYSQLLLYPYGYTTQSIPDKTELNQVAKSAVAAL-------KSL
YGTSYKYGSIITTIYQASGGSIDWSYNQGIKYSFTFELRDTGRYGFLLPASQIIPTAQET
WLGVLTIMEHTVNN*
>P1;1hdu_E
structureX:1hdu_E:1: : 307  : :  : : -1.00 :-1.00
ARSTNTFNYATYHTLDEIYDFMDLLVAQHPELVSKLQIGRSYEGRPIYVLKFSTGGSNRP
AIWIDLGIHSREWITQATGVWFAKKFTENYGQNPSFTAILDSMDIFLEIVTNPNGFAFTH
SENRLWRKTRSVTSSSLCVGVDANRNWDAGFGKAGASSSPCSETYHGKYANSEVEVKSIV
DFVKNHGNFKAFLSIHSYSQLLLYPYGYTTQSIPDKTELNQVAKSAVAAL-------KSL
YGTSYKYGSIITTIYQASGGSIDWSYNQGIKYSFTFELRDTGRYGFLLPASQIIPTAQET
WLGVLTIMEHTVNN*
>P1;1hee_A
structureX:1hee_A:1: : 307  : :  : : -1.00 :-1.00
ARSTNTFNYATYHTLDEIYDFMDLLVAQHPELVSKLQIGRSYEGRPIYVLKFSTGGSNRP
AIWIDLGIHSREWITQATGVWFAKKFTENYGQNPSFTAILDSMDIFLEIVTNPNGFAFTH
SENRLWRKTRSVTSSSLCVGVDANRNWDAGFGKAGASSSPCSETYHGKYANSEVEVKSIV
DFVKNHGNFKAFLSIHSYSQLLLYPYGYTTQSIPDKTELNQVAKSAVAAL-------KSL
YGTSYKYGSIITTIYQASGGSIDWSYNQGIKYSFTFELRDTGRYGFLLPASQIIPTAQET
WLGVLTIMEHTVNN*
>P1;target1
structureX:target1:1: : 314  : :  : : -1.00 :-1.00
ARSTNTFNYATYHTLDELYDFMDLLVAQHPELVSKLQLGRSYEGRPLYVLKYSTGGSNRP
VLWLDLGLHSREWLTQVTGVWFAKKFTENYGQNPSFTALLDSMDLYLELVTNPNGFVFTH
SENRLWRKTRSVTSSSLCVGVDANRNWDVGYGKAGVSSSPCSETYHGKYANSEVEVKSLV
DFVKNHGNFKAYLSLVSYSQLLLYPYGYTTQSLPDKTELNQVAKSSVEELLLSQNSVKSL
YGTSYKYGSLLTTLYQVSGGSLDWSYNQGLKYSFTYELRDTGRYGFLLPASQLLPTVQET
WLGVLTLMEHTVNN*
