>P1;1y01_B
structureX:1y01_B:1: : 123  : :  : : -1.00 :-1.00
--LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHG
KKVADALTNAVAHVD-MPNAL-----------RVDPVNFKLL---SHCLLVTLAAH---L
PAEFTPAVHASLDKFLASVSTVL*
>P1;target
structureX:target:1: : 142  : :  : : -1.00 :-1.00
-VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHG
KKVADALTNAVAHVDDMPNALSALSDDEAHKERDDPVNDKLLSHCLLVTLAAHAPALAHL
PAEFTPAVHASLDKFLASVSTVD*
>P1;1z8u_D
structureX:1z8u_D:1: : 135  : :  : : -1.00 :-1.00
--LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHG
KKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLL---SHCLLVTLAAH---L
PAEFTPAVHASLDKFLASVSTVL*
>P1;1bz1_C
structureX:1bz1_C:1: : 137  : :  : : -1.00 :-1.00
MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHG
KKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLL---SHCLLVTLAAH---L
PAEFTPAVHASLDKFLASVSTVL*
