>P1;1y01_B
structureX:1y01_B:1: : 126  : :  : : -1.00 :-1.00
--LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHG
KKVADALTNAVAHVD-MPNAL-----------RVDPVNFKLLSHCLLVTLAAH------L
PAEFTPAVHASLDKFLASVSTVLTSK--*
>P1;target
structureX:target:1: : 147  : :  : : -1.00 :-1.00
-VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHG
KKVADALTNAVAHVDDMPNALSALSDDEAHKERDDPVNDKLLSHCLLVTLAAHAPALAHL
PAEFTPAVHASLDKFLASVSTVDTSKYR*
>P1;1z8u_D
structureX:1z8u_D:1: : 135  : :  : : -1.00 :-1.00
--LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHG
KKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAH------L
PAEFTPAVHASLDKFLASVSTVL-----*
>P1;1bz1_C
structureX:1bz1_C:1: : 142  : :  : : -1.00 :-1.00
MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHG
KKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAH------L
PAEFTPAVHASLDKFLASVSTVLTSKYR*
