>P1;1an2_A
structureX:1an2_A:1: : 86  : :  : : -1.00 :-1.00
---------ADKRAHHNALERKRRDHIKDSFHSLR---DSVPSLQGEKASRAQILDKATE
YIQYMRRKNHTHQQDIDDLKRQNALLEQQVRALEKARS*
>P1;1hlo_A
structureX:1hlo_A:1: : 80  : :  : : -1.00 :-1.00
NDDIEVESDADKRAHHNALERKRRDHIKDSFHSLR---DSVPSLQGEKASRAQILDKATE
YIQYMRRKNHTHQQDIDDLKRQN---------------*
>P1;1nlw_B
structureX:1nlw_B:1: : 76  : :  : : -1.00 :-1.00
-----------KRAHHNALERKRRDHIKDSFHSLR---DSVPSLQGEKASRAQILDKATE
YIQYMRRKNHTHQQDIDDLKRQNALLEQQV--------*
>P1;targetB
structureX:targetB:1: : 83  : :  : : -1.00 :-1.00
----------DALAHHNALELDLADHIKDSFHSLSLFLDSVPSLQGEKASRAQILDKFTE
YIQYMRRKNHTHQQDIDDLKRQNALLEQQVRAL-----*
