>P1;targetA
structureX:targetA:1: : 89  : :  : : -1.00 :-1.00
---NVKRRTHNVLERQRRNELKRSFFAFRDQIPELENNEKAPKVVILKKFTATATATTAY
ILSVQAEEQKLISEEDLLRKRREQLKHKLEQL---*
>P1;1nkp_A
structureX:1nkp_A:1: : 88  : :  : : -1.00 :-1.00
GHMNVKRRTHNVLERQRRNELKRSFFALRDQIPELENNEKAPKVVILKK-------ATAY
ILSVQAEEQKLISEEDLLRKRREQLKHKLEQLGGC*
>P1;1a93_A
structureX:1a93_A:1: : 32  : :  : : -1.00 :-1.00
------------------------------------------------------------
CGGVQAEEQKLISEEDLLRKRREQLKHKLEQL---*
>P1;1nwq_A
structureX:1nwq_A:1: : 60  : :  : : -1.00 :-1.00
----------NSNEYRVRRE--------RNNIAVRKSRDKAKQ----------------R
NVETQQKVLELTSDNDRLRKRVEQLSRELDTLRG-*
